/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  GardenDesigners: () => import('#controllers/garden_designers_controller'),
  Generals: () => import('#controllers/generals_controller'),
  Homepages: () => import('#controllers/homepages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Plants: () => import('#controllers/plants_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
  Session: () => import('#controllers/session_controller'),
}
