/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'sortOrder', 'updatedAt', 'url', 'userId'] as const
  $columns = AccountLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: number
}

export class AccountProfileSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bannerUrl', 'bio', 'createdAt', 'displayName', 'id', 'location', 'notificationsClearedAt', 'notificationsSeenAt', 'premiumRenewsAt', 'premiumStartedAt', 'rewardPoints', 'scannerMonthlyLimit', 'subscriptionPlan', 'updatedAt', 'userId', 'websiteUrl'] as const
  $columns = AccountProfileSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bannerUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string | null
  @column.dateTime()
  declare notificationsClearedAt: DateTime | null
  @column.dateTime()
  declare notificationsSeenAt: DateTime | null
  @column.dateTime()
  declare premiumRenewsAt: DateTime | null
  @column.dateTime()
  declare premiumStartedAt: DateTime | null
  @column()
  declare rewardPoints: number
  @column()
  declare scannerMonthlyLimit: number
  @column()
  declare subscriptionPlan: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare websiteUrl: string | null
}

export class AdminAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorEmail', 'actorUserId', 'createdAt', 'id', 'ipAddress', 'summary', 'targetId', 'targetType'] as const
  $columns = AdminAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorEmail: string
  @column()
  declare actorUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare summary: string
  @column()
  declare targetId: string | null
  @column()
  declare targetType: string
}

export class CommunityPostSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'mediaType', 'mediaUrl', 'updatedAt', 'userId', 'visibility'] as const
  $columns = CommunityPostSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mediaType: string
  @column()
  declare mediaUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare visibility: string
}

export class FavoriteAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'favoriteUserId', 'id', 'updatedAt', 'userId'] as const
  $columns = FavoriteAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare favoriteUserId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class FollowSchema extends BaseModel {
  static $columns = ['createdAt', 'followerId', 'followingId', 'id', 'updatedAt'] as const
  $columns = FollowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare followerId: number
  @column()
  declare followingId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GardenerProfileSchema extends BaseModel {
  static $columns = ['availabilitySchedule', 'bio', 'createdAt', 'experienceYears', 'headline', 'hourlyRate', 'id', 'isAvailable', 'paymentMethods', 'payoutCardBrand', 'payoutCardLastFour', 'payoutCardholderName', 'payoutPaypalEmail', 'portfolioUrl', 'publicPhone', 'ratingAverage', 'ratingCount', 'serviceArea', 'servicesOffered', 'updatedAt', 'userId'] as const
  $columns = GardenerProfileSchema.$columns
  @column()
  declare availabilitySchedule: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare experienceYears: number
  @column()
  declare headline: string | null
  @column()
  declare hourlyRate: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAvailable: boolean
  @column()
  declare paymentMethods: string | null
  @column()
  declare payoutCardBrand: string | null
  @column()
  declare payoutCardLastFour: string | null
  @column()
  declare payoutCardholderName: string | null
  @column()
  declare payoutPaypalEmail: string | null
  @column()
  declare portfolioUrl: string | null
  @column()
  declare publicPhone: string | null
  @column()
  declare ratingAverage: number
  @column()
  declare ratingCount: number
  @column()
  declare serviceArea: string | null
  @column()
  declare servicesOffered: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class GardenerServiceSchema extends BaseModel {
  static $columns = ['basePrice', 'createdAt', 'description', 'durationMinutes', 'gardenerProfileId', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = GardenerServiceSchema.$columns
  @column()
  declare basePrice: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare durationMinutes: number | null
  @column()
  declare gardenerProfileId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NurseryCatalogCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'nurseryProfileId', 'sortOrder', 'updatedAt'] as const
  $columns = NurseryCatalogCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare nurseryProfileId: number
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NurseryProductSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'id', 'imageUrl', 'isActive', 'name', 'nurseryProfileId', 'price', 'stock', 'updatedAt'] as const
  $columns = NurseryProductSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare nurseryProfileId: number
  @column()
  declare price: number | null
  @column()
  declare stock: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NurseryProfileSchema extends BaseModel {
  static $columns = ['address', 'bannerUrl', 'city', 'createdAt', 'description', 'id', 'isActive', 'latitude', 'logoUrl', 'longitude', 'nurseryName', 'nurserySlug', 'openingHours', 'ownerName', 'paymentMethods', 'payoutCardBrand', 'payoutCardLastFour', 'payoutCardholderName', 'payoutPaypalEmail', 'publicEmail', 'publicPhone', 'ratingAverage', 'ratingCount', 'servicesOffered', 'updatedAt', 'userId'] as const
  $columns = NurseryProfileSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare bannerUrl: string | null
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare latitude: number | null
  @column()
  declare logoUrl: string | null
  @column()
  declare longitude: number | null
  @column()
  declare nurseryName: string
  @column()
  declare nurserySlug: string | null
  @column()
  declare openingHours: string | null
  @column()
  declare ownerName: string
  @column()
  declare paymentMethods: string | null
  @column()
  declare payoutCardBrand: string | null
  @column()
  declare payoutCardLastFour: string | null
  @column()
  declare payoutCardholderName: string | null
  @column()
  declare payoutPaypalEmail: string | null
  @column()
  declare publicEmail: string | null
  @column()
  declare publicPhone: string | null
  @column()
  declare ratingAverage: number
  @column()
  declare ratingCount: number
  @column()
  declare servicesOffered: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PlantScanSchema extends BaseModel {
  static $columns = ['accountProfileId', 'causes', 'confidence', 'createdAt', 'healthStatus', 'id', 'imageHash', 'matches', 'premiumInsights', 'reliabilityLevel', 'scanSummary', 'species', 'subscriptionPlan', 'updatedAt', 'userId'] as const
  $columns = PlantScanSchema.$columns
  @column()
  declare accountProfileId: number | null
  @column()
  declare causes: string | null
  @column()
  declare confidence: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare healthStatus: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageHash: string | null
  @column()
  declare matches: string | null
  @column()
  declare premiumInsights: string | null
  @column()
  declare reliabilityLevel: string | null
  @column()
  declare scanSummary: string | null
  @column()
  declare species: string
  @column()
  declare subscriptionPlan: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PostCommentSchema extends BaseModel {
  static $columns = ['body', 'communityPostId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = PostCommentSchema.$columns
  @column()
  declare body: string
  @column()
  declare communityPostId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PostHashtagSchema extends BaseModel {
  static $columns = ['communityPostId', 'createdAt', 'id', 'tag', 'updatedAt'] as const
  $columns = PostHashtagSchema.$columns
  @column()
  declare communityPostId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tag: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostPollOptionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'postPollId', 'sortOrder', 'updatedAt'] as const
  $columns = PostPollOptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare postPollId: number
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostPollVoteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postPollId', 'postPollOptionId', 'updatedAt', 'userId'] as const
  $columns = PostPollVoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postPollId: number
  @column()
  declare postPollOptionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PostPollSchema extends BaseModel {
  static $columns = ['communityPostId', 'createdAt', 'id', 'question', 'updatedAt'] as const
  $columns = PostPollSchema.$columns
  @column()
  declare communityPostId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare question: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostReactionSchema extends BaseModel {
  static $columns = ['communityPostId', 'createdAt', 'id', 'type', 'updatedAt', 'userId'] as const
  $columns = PostReactionSchema.$columns
  @column()
  declare communityPostId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ProfileReviewSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'gardenerProfileId', 'id', 'nurseryProfileId', 'rating', 'reviewerName', 'reviewerUserId', 'updatedAt'] as const
  $columns = ProfileReviewSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gardenerProfileId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nurseryProfileId: number | null
  @column()
  declare rating: number
  @column()
  declare reviewerName: string | null
  @column()
  declare reviewerUserId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServiceRequestSchema extends BaseModel {
  static $columns = ['address', 'arrivalWindowEnd', 'arrivalWindowStart', 'budget', 'clientConfirmedAt', 'clientHiddenAt', 'clientUserId', 'completedAt', 'createdAt', 'discountAmount', 'discountPercent', 'finalAmount', 'gardenerConfirmedAt', 'gardenerHiddenAt', 'gardenerProfileId', 'gardenerResponse', 'googlePlaceId', 'heldAmount', 'id', 'latitude', 'locationRemovedAt', 'longitude', 'notes', 'nurseryProfileId', 'paymentBrand', 'paymentHeldAt', 'paymentLastFour', 'paymentMethod', 'paymentRefundedAt', 'paymentReleasedAt', 'paymentStatus', 'pointsRedeemed', 'pointsRefundedAt', 'refundedAmount', 'releasedAmount', 'rewardAwardedAt', 'rewardPointsAwarded', 'scheduledFor', 'serviceType', 'status', 'updatedAt', 'verifiedAt'] as const
  $columns = ServiceRequestSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare arrivalWindowEnd: string | null
  @column()
  declare arrivalWindowStart: string | null
  @column()
  declare budget: number | null
  @column.dateTime()
  declare clientConfirmedAt: DateTime | null
  @column.dateTime()
  declare clientHiddenAt: DateTime | null
  @column()
  declare clientUserId: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discountAmount: number
  @column()
  declare discountPercent: number
  @column()
  declare finalAmount: number | null
  @column.dateTime()
  declare gardenerConfirmedAt: DateTime | null
  @column.dateTime()
  declare gardenerHiddenAt: DateTime | null
  @column()
  declare gardenerProfileId: number | null
  @column()
  declare gardenerResponse: string | null
  @column()
  declare googlePlaceId: string | null
  @column()
  declare heldAmount: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number | null
  @column.dateTime()
  declare locationRemovedAt: DateTime | null
  @column()
  declare longitude: number | null
  @column()
  declare notes: string | null
  @column()
  declare nurseryProfileId: number | null
  @column()
  declare paymentBrand: string | null
  @column.dateTime()
  declare paymentHeldAt: DateTime | null
  @column()
  declare paymentLastFour: string | null
  @column()
  declare paymentMethod: string | null
  @column.dateTime()
  declare paymentRefundedAt: DateTime | null
  @column.dateTime()
  declare paymentReleasedAt: DateTime | null
  @column()
  declare paymentStatus: string | null
  @column()
  declare pointsRedeemed: number
  @column.dateTime()
  declare pointsRefundedAt: DateTime | null
  @column()
  declare refundedAmount: number | null
  @column()
  declare releasedAmount: number | null
  @column.dateTime()
  declare rewardAwardedAt: DateTime | null
  @column()
  declare rewardPointsAwarded: number
  @column.dateTime()
  declare scheduledFor: DateTime | null
  @column()
  declare serviceType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['accessLevel', 'createdAt', 'dui', 'email', 'firstName', 'id', 'lastName', 'password', 'phone', 'profilePicture', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare accessLevel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dui: string | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare profilePicture: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
