/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GardenerProfileSchema extends BaseModel {
  static $columns = [
    'availabilitySchedule',
    'createdAt',
    'id',
    'servicesOffered',
    'updatedAt',
    'userId',
  ] as const
  $columns = GardenerProfileSchema.$columns
  @column()
  declare availabilitySchedule: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare servicesOffered: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class NurseryProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nurseryName', 'ownerName', 'updatedAt', 'userId'] as const
  $columns = NurseryProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nurseryName: string
  @column()
  declare ownerName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dui',
    'email',
    'firstName',
    'id',
    'lastName',
    'password',
    'phone',
    'profilePicture',
    'role',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dui: string | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare profilePicture: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
